parameters:
    yousign_v2_uri: "%env(default::YOUSIGN_V2_URI)%"
    yousign_v2_access_key: "%env(default::YOUSIGN_V2_ACCESS_KEY)%"
    yousign_v2_token: "%env(default::YOUSIGN_V2_TOKEN)%"
    yousign_v2_app_uri: "%env(default::YOUSIGN_V2_APP_URI)%"
    yousign_v3_uri: "%env(default::YOUSIGN_V3_URI)%"
    yousign_v3_token: "%env(default::YOUSIGN_V3_TOKEN)%"
    yousign_v3_access_key: "%env(default::YOUSIGN_V3_ACCESS_KEY)%"
    yousign_v3_workspace_id: "%env(default::YOUSIGN_V3_WORKSPACE_ID)%"

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $webhookParsers: !tagged_iterator 'yousign.webhook_parser'
            $clientImplementations: !tagged_iterator { tag: 'yousign.client_implementation', index_by: 'key' }

    _instanceof:
        ComCompany\YousignBundle\Service\WebhookParserInterface:
            tags: [ name: 'yousign.webhook_parser' ]

    ComCompany\YousignBundle\:
        resource: '../../'
        exclude:
            - '../../DTO/'

    ComCompany\YousignBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    yousign_bundle.v3_client:
        class: 'Symfony\Component\HttpClient\HttpClient'
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            $defaultOptions:
                headers:
                    content-type: 'application/json'
                    Authorization: 'Bearer %yousign_v3_token%'
                base_uri: '%yousign_v3_uri%'

    yousign_bundle.v2_client:
        class: 'Symfony\Component\HttpClient\HttpClient'
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            $defaultOptions:
                headers:
                    content-type: 'application/json'
                    Authorization: 'Bearer %yousign_v2_token%'
                base_uri: '%yousign_v2_uri%'

    ComCompany\YousignBundle\Service\YousignV3\ClientYousign:
        tags:
            - { name: 'yousign.client_implementation', key: 'v3' }
        arguments:
            $httpClient: '@yousign_bundle.v3_client'

    ComCompany\YousignBundle\Service\YousignV2\ClientYousign:
        tags:
            - { name: 'yousign.client_implementation', key: 'v3' }
        arguments:
            $httpClient: '@yousign_bundle.v2_client'
        calls:
            - setAppUri: ['%yousign_v2_app_uri%']
