services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $webhookParsers: !tagged_iterator 'yousign.webhook_parser'

    _instanceof:
        ComCompany\YousignBundle\Service\WebhookParserInterface:
            tags: [ name: 'yousign.webhook_parser' ]

    ComCompany\YousignBundle\:
        resource: '../../'
        exclude:
            - '../../DTO/'

    ComCompany\YousignBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    yousign_bundle.v3_client:
        class: 'Symfony\Component\HttpClient\HttpClient'
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            $defaultOptions:
                headers:
                    content-type: 'application/json'
                    Authorization: 'Bearer %env(resolve:YOUSIGN_V3_TOKEN, "default")%'
                base_uri: '%env(resolve:YOUSIGN_V3_URI, "default")%'

    yousign_bundle.v2_client:
        class: 'Symfony\Component\HttpClient\HttpClient'
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            $defaultOptions:
                headers:
                    content-type: 'application/json'
                    Authorization: 'Bearer %env(resolve:YOUSIGN_V2_TOKEN, "default")%'
                base_uri: '%env(resolve:YOUSIGN_V2_URI, "default")%'

    ComCompany\YousignBundle\Service\YousignV3\ClientYousign:
        arguments:
            $httpClient: '@yousign_bundle.v3_client'

    ComCompany\YousignBundle\Service\YousignV2\ClientYousign:
        arguments:
            $httpClient: '@yousign_bundle.v2_client'
