services:
    yousign_bundle.v3_client:
        class: 'Symfony\Component\HttpClient\HttpClient'
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            $defaultOptions:
                headers:
                    content-type: 'application/json'
                    Authorization: 'Bearer %yousign_v3_token%'
                base_uri: '%yousign_v3_uri%'

    yousign_bundle.v2_client:
        class: 'Symfony\Component\HttpClient\HttpClient'
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            $defaultOptions:
                headers:
                    content-type: 'application/json'
                    Authorization: 'Bearer %yousign_v2_token%'
                base_uri: '%yousign_v2_uri%'

    ComCompany\YousignBundle\Service\YousignV3\ClientYousign:
        public: false
        autowire: true
        arguments:
            $httpClient: '@yousign_bundle.v3_client'

    ComCompany\YousignBundle\Service\YousignV2\ClientYousign:
        public: false
        autowire: true
        arguments:
            $httpClient: '@yousign_bundle.v2_client'

